<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LexisNexis.ProductManager.Core\LexisNexis.ProductManager.Core.csproj" />
		<ProjectReference Include="..\LexisNexis.ProductManager.Migrations\LexisNexis.ProductManager.Migrations.csproj" />
	</ItemGroup>

</Project>
